version: '3.3'

services:
  db:
    container_name: postres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: user
    networks:
      - backend
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - backend
  gateway:
    container_name: gateway
    image: gabrielenaretto/apigateway
    ports:
      - "8080:8080"
    labels:
      kompose.service.type: NodePort
      kompose.service.nodeport.port: "30000"
    networks:
      - backend
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=dataHub
    networks:
      - backend
  microservicedata:
    build:
      context: .                          #docker file path (. means root directory)
      dockerfile: Dockerfile
    image: microservicedata
    container_name: microServiceData
    ports:
      - "8082:8082"
    depends_on:
      - mongo
    networks:
      - backend
    environment:
      - spring.data.mongodb.authentication-database=admin
      - spring.data.mongodb.username=admin
      - spring.data.mongodb.password=admin
      - spring.data.mongodb.database=dataHub
      - spring.data.mongodb.port=27017
      - spring.data.mongodb.host=mongo

  microserviceuser:
    build:
      context: .                          #docker file path (. means root directory)
      dockerfile: Dockerfile
    image: gabrielenaretto/microserviceuser
    container_name: microServiceUser
    ports:
      - "8081:8081"
    depends_on:
      - db
    networks:
      - backend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/user
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_RABBITMQ_HOST=rabbitmq
      - spring_rabbitmq_port=5672
      - spring_rabbitmq_username=guest
      - spring_rabbitmq_password=guest

volumes:
  data : {}

networks:
  backend:
  